name: Common setup
description: Common setup steps for jobs that use Nix
inputs:
  cachix_token:
    description: 'The Cachix token to use for caching'
    required: true
runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@v27
      with:
          nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v15
      with:
        name: sumoduduk
        authToken: ${{ inputs.cachix_token }}

    - name: Create deploy directory
      shell: bash
      run: mkdir -p binaries
