name: "CI mac ARM"

on:
  workflow_dispatch:

jobs:
  sandbox-build-apple-arm:
    name: sandbox build for apple ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
            nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: nix-community

      - name: Build termusix for aarch64-apple-darwin in sandbox mode
        run: |
          cd ./nix/pkgs
          nix-build --option sandbox true -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'
          ./result/bin/termusix --version

