name: "CI mac x86_64"

on:
  workflow_dispatch:

jobs:
  sandbox-build-for-apple-intel:
    name: sandbox build for apple x86_64
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
            nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: nix-community

      - name: Build termusix for x86_64-apple-darwin in sandbox mode
        run: |
          cd ./nix/pkgs
          nix-build --option sandbox true -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'
          ./result/bin/termusix --version
