name: "Build scoop"
on:
  workflow_dispatch:
jobs:
  # build-scoop-appmanifest:
  #   name: build scoop app manifest with nix
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/common-setup
  #       with:
  #         cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  #     - name: Build app manifest
  #       run: nix build .#termusix-appmanifest --show-trace --log-lines 10000
  #
  #     - name: copy app manifest
  #       run: | 
  #         mkdir -p json_file
  #         cp result/termusix.json json_file/termusix.json
  #
  #     - name: upload json file
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: appmanifest-termusix
  #         path: json_file/termusix.json
  test-install-with-scoop:
    name: test install app manifest with scoop
    runs-on: windows-latest
    steps:
      - name: Get latest release version
        id: get_latest_release
        run: |
          $release = gh release view --json tagName --jq ".tagName"
          echo "Latest release version: $release"
          echo "::set-output name=version::$release"
          shell: pwsh
      - name: Download the latest release file
        run: |
          $version = "${{ steps.get_latest_release.outputs.version }}"
          $url = "https://github.com/sumoduduk/termusix/releases/download/$version/termusix-x86_64-windows.exe"
          echo "Downloading file from: $url"
          Invoke-WebRequest -Uri $url -OutFile "termusix-x86_64-windows.exe"
        shell: pwsh
      - name: Calculate SHA256
        id: calculate_sha
        run: |
          $hash = Get-FileHash -Path "termusix-x86_64-windows.exe" -Algorithm SHA256
          echo "SHA256: $($hash.Hash)"
          echo "::set-output name=sha256sum::$($hash.Hash)"
        shell: pwsh
      - name: Write JSON file
        run: |
          $version = "${{ steps.get_latest_release.outputs.version }}"
          $sha256sum = "${{ steps.calculate_sha.outputs.sha256sum }}"

          $jsonContent = @"
           {
           "version" : "$version",
           "homepage": "https://github.com/sumoduduk/termusix",
           "license": "GPL-3.0",
           "architecture": {
             "64bit": {
               "url": "https://github.com/sumoduduk/termusix/releases/download/v$version/termusix-x86_64-windows.exe#/termusix.exe",
               "hash": "$sha256sum"
             }
           },
           "bin": "termusix.exe",
           "checkver": "github",
           "autoupdate": {
             "architecture": {
               "64bit": {
                 "url": "https://github.com/sumoduduk/termusix/releases/download/v$version/termusix-x86_64-windows.exe#/termusix.exe"
               }
             }
           }
          }
           "@
           $jsonContent | Set-Content -Path "termusix.json"
           shell: pwsh
      - name: install scoop
        uses: MinoruSekine/setup-scoop@v4
      - name: install termusix
        run: |
          scoop install termusix.json
      - name: run the app
        run: termusix.exe --help
