name: "Build scoop"
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test-install-with-scoop:
    name: Test install app manifest with scoop
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get latest release version
        id: get_latest_release
        run: |
          $release = gh release view --json tagName --jq ".tagName"
          echo "Latest release version: $release"
          echo "version=$release" >> $GITHUB_ENV
        shell: pwsh
      - name: Download the latest release file
        run: |
          $version = "${{ env.version }}"
          $url = "https://github.com/sumoduduk/termusix/releases/download/$version/termusix-x86_64-windows.exe"
          echo "Downloading file from: $url"
          Invoke-WebRequest -Uri $url -OutFile "termusix-x86_64-windows.exe"
        shell: pwsh
      - name: Calculate SHA256
        id: calculate_sha
        run: |
          $hash = Get-FileHash -Path "termusix-x86_64-windows.exe" -Algorithm SHA256
          echo "SHA256: $($hash.Hash)"
          echo "sha256sum=$($hash.Hash)" >> $GITHUB_ENV
        shell: pwsh
      - name: Write JSON file
        run: |
          $version = "${{ env.version }}"
          $sha256sum = "${{ env.sha256sum }}"

          $jsonContent = @'{
            "version" : "$version",
            "homepage": "https://github.com/sumoduduk/termusix",
            "description" : "A terminal-based music player with a user-friendly terminal UI, built with Rust",
            "license": "GPL-3.0",
            "architecture": {
              "64bit": {
                "url": "https://github.com/sumoduduk/termusix/releases/download/v$version/termusix-x86_64-windows.exe#/termusix.exe",
                "hash": "$sha256sum"
              }
            },
            "bin": "termusix.exe",
            "checkver": "github",
            "autoupdate": {
              "architecture": {
                "64bit": {
                  "url": "https://github.com/sumoduduk/termusix/releases/download/v$version/termusix-x86_64-windows.exe#/termusix.exe"
                }
              }
            }
          }'@

          $jsonContent | Set-Content -Path "termusix.json"
        shell: pwsh
      - name: Install scoop
        uses: MinoruSekine/setup-scoop@v4
      - name: Install Termusix
        run: |
          scoop install termusix.json
        shell: pwsh
      - name: Run the app
        run: termusix.exe --help
        shell: pwsh
